### PR TITLE
Add latest MDM categories

### PR DESCRIPTION
**Pull request by michaelstingl**
Issue: https://github.com/owncloud/docs-client-ios-app/issues/92
Blocked by https://github.com/owncloud/docs-client-ios-app/pull/64

1) update `mdm_tables.adoc` from iOS app repo (only needed for local builds, can be removed after https://github.com/owncloud/docs-client-ios-app/pull/64 merge)
2) add MDM categories to` mdm.adoc`

### CODE REVIEW

**Comment by mmattel** [comment]
I have taken a look to this PR and propose NOT to implement the current changes to the mdm table in this repo but add the changes to [configuration.adoc](https://github.com/owncloud/ios-app/blob/master/doc/configuration.adoc) in the IOS repo. That file is, as far I know autogenerated and all changes should go there. The text changes and new content referenced by tags can go into this document.

When the changes have been added into configuration.adoc and removed from this PR, I will adapt this PR to include the file based on the git tag. This was already discussed and gives us the ability to freeze content for a IOS major/minor release and also link our "next" to the master version of the IOS repo.

We use the method of including "foreign" content successfully for a while now and it works very well.

Note that it was planned to auto-generate images and store them in [images](https://github.com/owncloud/ios-app/tree/master/doc/images/) which will get linked here too, but if you look into the content of that folder, you see text strings instead of images... also see the readme.md for what folder should have which content.

@hosy fyi

**Comment by michaelstingl** [comment]
> When the changes have been added into configuration.adoc and removed from this PR, I will adapt this PR

The `mdm_tables.adoc` in this PR is a copy of the [`configuration.adoc`](https://github.com/owncloud/ios-app/blob/master/doc/configuration.adoc) from the IOS repo. It should be deleted before the merge.

**Comment by mmattel** [comment]
I need clarification:

1. does the `configuration.adoc` at the ios repo contain all changes you have poropsed here?
2. if not, will the configuration.adoc file get updated and when

**Comment by michaelstingl** [comment]
> * does the `configuration.adoc` at the ios repo contain all changes you have proposed here?

yes

**Comment by mmattel** [comment]
I just have made the first changes according the discussion above. Local build runs fine and tests show that no missing tags are present. Note that no checks have been made with regards to correctness of the source content.

**Review by mmattel — APPROVED** [review]

**Comment by mmattel** [comment]
Backport to 11.10 only but needs checking if the include source has all data and omit those things which are not present.

**Pull request merged**
